Search.appendIndex(
    [
                {
            "fqsen": "\\Discord\\Http\\Bucket",
            "name": "Bucket",
            "summary": "Represents\u0020a\u0020rate\u002Dlimit\u0020bucket.",
            "url": "classes/Discord-Http-Bucket.html"
        },                {
            "fqsen": "\\Discord\\Http\\Bucket\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Bucket\u0020constructor.",
            "url": "classes/Discord-Http-Bucket.html#method___construct"
        },                {
            "fqsen": "\\Discord\\Http\\Bucket\u003A\u003Aenqueue\u0028\u0029",
            "name": "enqueue",
            "summary": "Enqueue\u0020a\u0020request.",
            "url": "classes/Discord-Http-Bucket.html#method_enqueue"
        },                {
            "fqsen": "\\Discord\\Http\\Bucket\u003A\u003AcheckQueue\u0028\u0029",
            "name": "checkQueue",
            "summary": "Checks\u0020for\u0020requests\u0020in\u0020the\u0020bucket.",
            "url": "classes/Discord-Http-Bucket.html#method_checkQueue"
        },                {
            "fqsen": "\\Discord\\Http\\Bucket\u003A\u003A__checkQueue\u0028\u0029",
            "name": "__checkQueue",
            "summary": "",
            "url": "classes/Discord-Http-Bucket.html#method___checkQueue"
        },                {
            "fqsen": "\\Discord\\Http\\Bucket\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Converts\u0020a\u0020bucket\u0020to\u0020a\u0020user\u002Dreadable\u0020string.",
            "url": "classes/Discord-Http-Bucket.html#method___toString"
        },                {
            "fqsen": "\\Discord\\Http\\Bucket\u003A\u003A\u0024queue",
            "name": "queue",
            "summary": "Request\u0020queue.",
            "url": "classes/Discord-Http-Bucket.html#property_queue"
        },                {
            "fqsen": "\\Discord\\Http\\Bucket\u003A\u003A\u0024name",
            "name": "name",
            "summary": "Bucket\u0020name.",
            "url": "classes/Discord-Http-Bucket.html#property_name"
        },                {
            "fqsen": "\\Discord\\Http\\Bucket\u003A\u003A\u0024loop",
            "name": "loop",
            "summary": "ReactPHP\u0020event\u0020loop.",
            "url": "classes/Discord-Http-Bucket.html#property_loop"
        },                {
            "fqsen": "\\Discord\\Http\\Bucket\u003A\u003A\u0024logger",
            "name": "logger",
            "summary": "HTTP\u0020logger.",
            "url": "classes/Discord-Http-Bucket.html#property_logger"
        },                {
            "fqsen": "\\Discord\\Http\\Bucket\u003A\u003A\u0024runRequest",
            "name": "runRequest",
            "summary": "Callback\u0020for\u0020when\u0020a\u0020request\u0020is\u0020ready.",
            "url": "classes/Discord-Http-Bucket.html#property_runRequest"
        },                {
            "fqsen": "\\Discord\\Http\\Bucket\u003A\u003A\u0024checkerRunning",
            "name": "checkerRunning",
            "summary": "Whether\u0020we\u0020are\u0020checking\u0020the\u0020queue.",
            "url": "classes/Discord-Http-Bucket.html#property_checkerRunning"
        },                {
            "fqsen": "\\Discord\\Http\\Bucket\u003A\u003A\u0024requestLimit",
            "name": "requestLimit",
            "summary": "Number\u0020of\u0020requests\u0020allowed\u0020before\u0020reset.",
            "url": "classes/Discord-Http-Bucket.html#property_requestLimit"
        },                {
            "fqsen": "\\Discord\\Http\\Bucket\u003A\u003A\u0024requestRemaining",
            "name": "requestRemaining",
            "summary": "Number\u0020of\u0020remaining\u0020requests\u0020before\u0020reset.",
            "url": "classes/Discord-Http-Bucket.html#property_requestRemaining"
        },                {
            "fqsen": "\\Discord\\Http\\Bucket\u003A\u003A\u0024resetTimer",
            "name": "resetTimer",
            "summary": "Timer\u0020to\u0020reset\u0020the\u0020bucket.",
            "url": "classes/Discord-Http-Bucket.html#property_resetTimer"
        },                {
            "fqsen": "\\Discord\\Http\\Bucket\u003A\u003A\u0024promiseV3",
            "name": "promiseV3",
            "summary": "Whether\u0020react\/promise\u0020v3\u0020is\u0020used,\u0020if\u0020false,\u0020using\u0020v2.",
            "url": "classes/Discord-Http-Bucket.html#property_promiseV3"
        },                {
            "fqsen": "\\Discord\\Http\\DriverInterface",
            "name": "DriverInterface",
            "summary": "Interface\u0020for\u0020an\u0020HTTP\u0020driver.",
            "url": "classes/Discord-Http-DriverInterface.html"
        },                {
            "fqsen": "\\Discord\\Http\\DriverInterface\u003A\u003ArunRequest\u0028\u0029",
            "name": "runRequest",
            "summary": "Runs\u0020a\u0020request.",
            "url": "classes/Discord-Http-DriverInterface.html#method_runRequest"
        },                {
            "fqsen": "\\Discord\\Http\\Drivers\\Guzzle",
            "name": "Guzzle",
            "summary": "guzzlehttp\/guzzle\u0020driver\u0020for\u0020Discord\u0020HTTP\u0020client.\u0020\u0028still\u0020with\u0020React\u0020Promise\u0029.",
            "url": "classes/Discord-Http-Drivers-Guzzle.html"
        },                {
            "fqsen": "\\Discord\\Http\\Drivers\\Guzzle\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructs\u0020the\u0020Guzzle\u0020driver.",
            "url": "classes/Discord-Http-Drivers-Guzzle.html#method___construct"
        },                {
            "fqsen": "\\Discord\\Http\\Drivers\\Guzzle\u003A\u003ArunRequest\u0028\u0029",
            "name": "runRequest",
            "summary": "Runs\u0020a\u0020request.",
            "url": "classes/Discord-Http-Drivers-Guzzle.html#method_runRequest"
        },                {
            "fqsen": "\\Discord\\Http\\Drivers\\Guzzle\u003A\u003A\u0024loop",
            "name": "loop",
            "summary": "ReactPHP\u0020event\u0020loop.",
            "url": "classes/Discord-Http-Drivers-Guzzle.html#property_loop"
        },                {
            "fqsen": "\\Discord\\Http\\Drivers\\Guzzle\u003A\u003A\u0024client",
            "name": "client",
            "summary": "GuzzleHTTP\/Guzzle\u0020client.",
            "url": "classes/Discord-Http-Drivers-Guzzle.html#property_client"
        },                {
            "fqsen": "\\Discord\\Http\\Drivers\\React",
            "name": "React",
            "summary": "react\/http\u0020driver\u0020for\u0020Discord\u0020HTTP\u0020client.",
            "url": "classes/Discord-Http-Drivers-React.html"
        },                {
            "fqsen": "\\Discord\\Http\\Drivers\\React\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructs\u0020the\u0020React\u0020driver.",
            "url": "classes/Discord-Http-Drivers-React.html#method___construct"
        },                {
            "fqsen": "\\Discord\\Http\\Drivers\\React\u003A\u003ArunRequest\u0028\u0029",
            "name": "runRequest",
            "summary": "Runs\u0020the\u0020request\u0020using\u0020the\u0020React\u0020HTTP\u0020client.",
            "url": "classes/Discord-Http-Drivers-React.html#method_runRequest"
        },                {
            "fqsen": "\\Discord\\Http\\Drivers\\React\u003A\u003A\u0024loop",
            "name": "loop",
            "summary": "ReactPHP\u0020event\u0020loop.",
            "url": "classes/Discord-Http-Drivers-React.html#property_loop"
        },                {
            "fqsen": "\\Discord\\Http\\Drivers\\React\u003A\u003A\u0024browser",
            "name": "browser",
            "summary": "ReactPHP\/HTTP\u0020browser.",
            "url": "classes/Discord-Http-Drivers-React.html#property_browser"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint",
            "name": "Endpoint",
            "summary": "",
            "url": "classes/Discord-Http-Endpoint.html"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Creates\u0020an\u0020endpoint\u0020class.",
            "url": "classes/Discord-Http-Endpoint.html#method___construct"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGATEWAY",
            "name": "GATEWAY",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_GATEWAY"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGATEWAY_BOT",
            "name": "GATEWAY_BOT",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_GATEWAY_BOT"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AAPPLICATION_SKUS",
            "name": "APPLICATION_SKUS",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_APPLICATION_SKUS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AAPPLICATION_EMOJIS",
            "name": "APPLICATION_EMOJIS",
            "summary": "GET,\u0020POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_APPLICATION_EMOJIS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AAPPLICATION_EMOJI",
            "name": "APPLICATION_EMOJI",
            "summary": "GET,\u0020PATCH,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_APPLICATION_EMOJI"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AAPPLICATION_ENTITLEMENTS",
            "name": "APPLICATION_ENTITLEMENTS",
            "summary": "GET,\u0020POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_APPLICATION_ENTITLEMENTS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AAPPLICATION_ENTITLEMENT",
            "name": "APPLICATION_ENTITLEMENT",
            "summary": "DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_APPLICATION_ENTITLEMENT"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AAPPLICATION_ENTITLEMENT_CONSUME",
            "name": "APPLICATION_ENTITLEMENT_CONSUME",
            "summary": "POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_APPLICATION_ENTITLEMENT_CONSUME"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGLOBAL_APPLICATION_COMMANDS",
            "name": "GLOBAL_APPLICATION_COMMANDS",
            "summary": "GET,\u0020POST,\u0020PUT",
            "url": "classes/Discord-Http-Endpoint.html#constant_GLOBAL_APPLICATION_COMMANDS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGLOBAL_APPLICATION_COMMAND",
            "name": "GLOBAL_APPLICATION_COMMAND",
            "summary": "GET,\u0020PATCH,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_GLOBAL_APPLICATION_COMMAND"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_APPLICATION_COMMANDS",
            "name": "GUILD_APPLICATION_COMMANDS",
            "summary": "GET,\u0020POST,\u0020PUT",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_APPLICATION_COMMANDS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_APPLICATION_COMMANDS_PERMISSIONS",
            "name": "GUILD_APPLICATION_COMMANDS_PERMISSIONS",
            "summary": "GET,\u0020PUT",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_APPLICATION_COMMANDS_PERMISSIONS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_APPLICATION_COMMAND",
            "name": "GUILD_APPLICATION_COMMAND",
            "summary": "GET,\u0020PATCH,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_APPLICATION_COMMAND"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_APPLICATION_COMMAND_PERMISSIONS",
            "name": "GUILD_APPLICATION_COMMAND_PERMISSIONS",
            "summary": "GET,\u0020PUT",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_APPLICATION_COMMAND_PERMISSIONS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AINTERACTION_RESPONSE",
            "name": "INTERACTION_RESPONSE",
            "summary": "POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_INTERACTION_RESPONSE"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ACREATE_INTERACTION_FOLLOW_UP",
            "name": "CREATE_INTERACTION_FOLLOW_UP",
            "summary": "POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_CREATE_INTERACTION_FOLLOW_UP"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AORIGINAL_INTERACTION_RESPONSE",
            "name": "ORIGINAL_INTERACTION_RESPONSE",
            "summary": "PATCH,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_ORIGINAL_INTERACTION_RESPONSE"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AINTERACTION_FOLLOW_UP",
            "name": "INTERACTION_FOLLOW_UP",
            "summary": "PATCH,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_INTERACTION_FOLLOW_UP"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ASKU_SUBSCRIPTIONS",
            "name": "SKU_SUBSCRIPTIONS",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_SKU_SUBSCRIPTIONS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ASKU_SUBSCRIPTION",
            "name": "SKU_SUBSCRIPTION",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_SKU_SUBSCRIPTION"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AAUDIT_LOG",
            "name": "AUDIT_LOG",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_AUDIT_LOG"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ACHANNEL",
            "name": "CHANNEL",
            "summary": "GET,\u0020PATCH,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_CHANNEL"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ACHANNEL_MESSAGES",
            "name": "CHANNEL_MESSAGES",
            "summary": "GET,\u0020POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_CHANNEL_MESSAGES"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ACHANNEL_MESSAGE",
            "name": "CHANNEL_MESSAGE",
            "summary": "GET,\u0020PATCH,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_CHANNEL_MESSAGE"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ACHANNEL_CROSSPOST_MESSAGE",
            "name": "CHANNEL_CROSSPOST_MESSAGE",
            "summary": "POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_CHANNEL_CROSSPOST_MESSAGE"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ACHANNEL_MESSAGES_BULK_DELETE",
            "name": "CHANNEL_MESSAGES_BULK_DELETE",
            "summary": "POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_CHANNEL_MESSAGES_BULK_DELETE"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ACHANNEL_PERMISSIONS",
            "name": "CHANNEL_PERMISSIONS",
            "summary": "PUT,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_CHANNEL_PERMISSIONS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ACHANNEL_INVITES",
            "name": "CHANNEL_INVITES",
            "summary": "GET,\u0020POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_CHANNEL_INVITES"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ACHANNEL_FOLLOW",
            "name": "CHANNEL_FOLLOW",
            "summary": "POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_CHANNEL_FOLLOW"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ACHANNEL_TYPING",
            "name": "CHANNEL_TYPING",
            "summary": "POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_CHANNEL_TYPING"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ACHANNEL_PINS",
            "name": "CHANNEL_PINS",
            "summary": "",
            "url": "classes/Discord-Http-Endpoint.html#constant_CHANNEL_PINS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ACHANNEL_PIN",
            "name": "CHANNEL_PIN",
            "summary": "",
            "url": "classes/Discord-Http-Endpoint.html#constant_CHANNEL_PIN"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ACHANNEL_MESSAGES_PINS",
            "name": "CHANNEL_MESSAGES_PINS",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_CHANNEL_MESSAGES_PINS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ACHANNEL_MESSAGES_PIN",
            "name": "CHANNEL_MESSAGES_PIN",
            "summary": "PUT,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_CHANNEL_MESSAGES_PIN"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ACHANNEL_THREADS",
            "name": "CHANNEL_THREADS",
            "summary": "POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_CHANNEL_THREADS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ACHANNEL_THREADS_SEARCH",
            "name": "CHANNEL_THREADS_SEARCH",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_CHANNEL_THREADS_SEARCH"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ACHANNEL_MESSAGE_THREADS",
            "name": "CHANNEL_MESSAGE_THREADS",
            "summary": "POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_CHANNEL_MESSAGE_THREADS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ACHANNEL_THREADS_ARCHIVED_PUBLIC",
            "name": "CHANNEL_THREADS_ARCHIVED_PUBLIC",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_CHANNEL_THREADS_ARCHIVED_PUBLIC"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ACHANNEL_THREADS_ARCHIVED_PRIVATE",
            "name": "CHANNEL_THREADS_ARCHIVED_PRIVATE",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_CHANNEL_THREADS_ARCHIVED_PRIVATE"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ACHANNEL_THREADS_ARCHIVED_PRIVATE_ME",
            "name": "CHANNEL_THREADS_ARCHIVED_PRIVATE_ME",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_CHANNEL_THREADS_ARCHIVED_PRIVATE_ME"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ACHANNEL_SEND_SOUNDBOARD_SOUND",
            "name": "CHANNEL_SEND_SOUNDBOARD_SOUND",
            "summary": "POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_CHANNEL_SEND_SOUNDBOARD_SOUND"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ACHANNEL_VOICE_STATUS",
            "name": "CHANNEL_VOICE_STATUS",
            "summary": "PUT",
            "url": "classes/Discord-Http-Endpoint.html#constant_CHANNEL_VOICE_STATUS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ACHANNEL_RECIPIENT",
            "name": "CHANNEL_RECIPIENT",
            "summary": "PUT,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_CHANNEL_RECIPIENT"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ATHREAD",
            "name": "THREAD",
            "summary": "GET,\u0020PATCH,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_THREAD"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ATHREAD_MEMBERS",
            "name": "THREAD_MEMBERS",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_THREAD_MEMBERS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ATHREAD_MEMBER",
            "name": "THREAD_MEMBER",
            "summary": "GET,\u0020PUT,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_THREAD_MEMBER"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ATHREAD_MEMBER_ME",
            "name": "THREAD_MEMBER_ME",
            "summary": "PUT,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_THREAD_MEMBER_ME"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AMESSAGE_REACTION_ALL",
            "name": "MESSAGE_REACTION_ALL",
            "summary": "GET,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_MESSAGE_REACTION_ALL"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AMESSAGE_REACTION_EMOJI",
            "name": "MESSAGE_REACTION_EMOJI",
            "summary": "GET,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_MESSAGE_REACTION_EMOJI"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AOWN_MESSAGE_REACTION",
            "name": "OWN_MESSAGE_REACTION",
            "summary": "PUT,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_OWN_MESSAGE_REACTION"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AUSER_MESSAGE_REACTION",
            "name": "USER_MESSAGE_REACTION",
            "summary": "DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_USER_MESSAGE_REACTION"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AMESSAGE_POLL",
            "name": "MESSAGE_POLL",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_MESSAGE_POLL"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AMESSAGE_POLL_ANSWER",
            "name": "MESSAGE_POLL_ANSWER",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_MESSAGE_POLL_ANSWER"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AMESSAGE_POLL_EXPIRE",
            "name": "MESSAGE_POLL_EXPIRE",
            "summary": "POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_MESSAGE_POLL_EXPIRE"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ACHANNEL_WEBHOOKS",
            "name": "CHANNEL_WEBHOOKS",
            "summary": "GET,\u0020POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_CHANNEL_WEBHOOKS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILDS",
            "name": "GUILDS",
            "summary": "POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILDS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD",
            "name": "GUILD",
            "summary": "GET,\u0020PATCH,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_NEW_MEMBER_WELCOME",
            "name": "GUILD_NEW_MEMBER_WELCOME",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_NEW_MEMBER_WELCOME"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_CHANNELS",
            "name": "GUILD_CHANNELS",
            "summary": "GET,\u0020POST,\u0020PATCH",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_CHANNELS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_THREADS_ACTIVE",
            "name": "GUILD_THREADS_ACTIVE",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_THREADS_ACTIVE"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_MESSAGES_SEARCH",
            "name": "GUILD_MESSAGES_SEARCH",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_MESSAGES_SEARCH"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_MEMBERS",
            "name": "GUILD_MEMBERS",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_MEMBERS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_MEMBERS_SEARCH",
            "name": "GUILD_MEMBERS_SEARCH",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_MEMBERS_SEARCH"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_MEMBER",
            "name": "GUILD_MEMBER",
            "summary": "GET,\u0020PATCH,\u0020PUT,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_MEMBER"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_MEMBER_SELF",
            "name": "GUILD_MEMBER_SELF",
            "summary": "PATCH",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_MEMBER_SELF"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_MEMBER_SELF_NICK",
            "name": "GUILD_MEMBER_SELF_NICK",
            "summary": "",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_MEMBER_SELF_NICK"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_MEMBER_ROLE",
            "name": "GUILD_MEMBER_ROLE",
            "summary": "PUT,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_MEMBER_ROLE"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_BANS",
            "name": "GUILD_BANS",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_BANS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_BAN",
            "name": "GUILD_BAN",
            "summary": "GET,\u0020PUT,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_BAN"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_BAN_BULK",
            "name": "GUILD_BAN_BULK",
            "summary": "POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_BAN_BULK"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_ROLES",
            "name": "GUILD_ROLES",
            "summary": "GET,\u0020PATCH",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_ROLES"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_ROLES_MEMBER_COUNTS",
            "name": "GUILD_ROLES_MEMBER_COUNTS",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_ROLES_MEMBER_COUNTS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_ROLE",
            "name": "GUILD_ROLE",
            "summary": "GET,\u0020POST,\u0020PATCH,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_ROLE"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_MFA",
            "name": "GUILD_MFA",
            "summary": "POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_MFA"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_INVITES",
            "name": "GUILD_INVITES",
            "summary": "GET,\u0020POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_INVITES"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_INTEGRATIONS",
            "name": "GUILD_INTEGRATIONS",
            "summary": "GET,\u0020POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_INTEGRATIONS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_INTEGRATION",
            "name": "GUILD_INTEGRATION",
            "summary": "PATCH,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_INTEGRATION"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_INTEGRATION_SYNC",
            "name": "GUILD_INTEGRATION_SYNC",
            "summary": "POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_INTEGRATION_SYNC"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_EMOJIS",
            "name": "GUILD_EMOJIS",
            "summary": "GET,\u0020POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_EMOJIS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_EMOJI",
            "name": "GUILD_EMOJI",
            "summary": "GET,\u0020PATCH,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_EMOJI"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_PREVIEW",
            "name": "GUILD_PREVIEW",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_PREVIEW"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_PRUNE",
            "name": "GUILD_PRUNE",
            "summary": "GET,\u0020POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_PRUNE"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_REGIONS",
            "name": "GUILD_REGIONS",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_REGIONS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_WIDGET_SETTINGS",
            "name": "GUILD_WIDGET_SETTINGS",
            "summary": "GET,\u0020PATCH",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_WIDGET_SETTINGS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_WIDGET",
            "name": "GUILD_WIDGET",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_WIDGET"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_WIDGET_IMAGE",
            "name": "GUILD_WIDGET_IMAGE",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_WIDGET_IMAGE"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_WELCOME_SCREEN",
            "name": "GUILD_WELCOME_SCREEN",
            "summary": "GET,\u0020PATCH",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_WELCOME_SCREEN"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_ONBOARDING",
            "name": "GUILD_ONBOARDING",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_ONBOARDING"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ALIST_VOICE_REGIONS",
            "name": "LIST_VOICE_REGIONS",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_LIST_VOICE_REGIONS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_USER_CURRENT_VOICE_STATE",
            "name": "GUILD_USER_CURRENT_VOICE_STATE",
            "summary": "GET,\u0020PATCH",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_USER_CURRENT_VOICE_STATE"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_USER_VOICE_STATE",
            "name": "GUILD_USER_VOICE_STATE",
            "summary": "GET,\u0020PATCH",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_USER_VOICE_STATE"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_VANITY_URL",
            "name": "GUILD_VANITY_URL",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_VANITY_URL"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_MEMBERSHIP_SCREENING",
            "name": "GUILD_MEMBERSHIP_SCREENING",
            "summary": "GET,\u0020PATCH",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_MEMBERSHIP_SCREENING"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_JOIN_REQUESTS",
            "name": "GUILD_JOIN_REQUESTS",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_JOIN_REQUESTS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_JOIN_REQUEST",
            "name": "GUILD_JOIN_REQUEST",
            "summary": "PATCH",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_JOIN_REQUEST"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_WEBHOOKS",
            "name": "GUILD_WEBHOOKS",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_WEBHOOKS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_STICKERS",
            "name": "GUILD_STICKERS",
            "summary": "GET,\u0020POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_STICKERS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_STICKER",
            "name": "GUILD_STICKER",
            "summary": "GET,\u0020PATCH,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_STICKER"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ASTICKER",
            "name": "STICKER",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_STICKER"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ASTICKER_PACKS",
            "name": "STICKER_PACKS",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_STICKER_PACKS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ASTICKER_PACK",
            "name": "STICKER_PACK",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_STICKER_PACK"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_SCHEDULED_EVENTS",
            "name": "GUILD_SCHEDULED_EVENTS",
            "summary": "GET,\u0020POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_SCHEDULED_EVENTS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_SCHEDULED_EVENT",
            "name": "GUILD_SCHEDULED_EVENT",
            "summary": "GET,\u0020PATCH,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_SCHEDULED_EVENT"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_SCHEDULED_EVENT_USERS",
            "name": "GUILD_SCHEDULED_EVENT_USERS",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_SCHEDULED_EVENT_USERS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_SCHEDULED_EVENT_USERS_COUNT",
            "name": "GUILD_SCHEDULED_EVENT_USERS_COUNT",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_SCHEDULED_EVENT_USERS_COUNT"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_SCHEDULED_EVENT_EXCEPTIONS",
            "name": "GUILD_SCHEDULED_EVENT_EXCEPTIONS",
            "summary": "GET,\u0020POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_SCHEDULED_EVENT_EXCEPTIONS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_SCHEDULED_EVENT_EXCEPTION",
            "name": "GUILD_SCHEDULED_EVENT_EXCEPTION",
            "summary": "PATCH,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_SCHEDULED_EVENT_EXCEPTION"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_SCHEDULED_EVENT_EXCEPTION_USERS",
            "name": "GUILD_SCHEDULED_EVENT_EXCEPTION_USERS",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_SCHEDULED_EVENT_EXCEPTION_USERS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_SOUNDBOARD_SOUNDS",
            "name": "GUILD_SOUNDBOARD_SOUNDS",
            "summary": "GET,\u0020POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_SOUNDBOARD_SOUNDS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_SOUNDBOARD_SOUND",
            "name": "GUILD_SOUNDBOARD_SOUND",
            "summary": "GET,\u0020PATCH,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_SOUNDBOARD_SOUND"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AINVITE",
            "name": "INVITE",
            "summary": "GET,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_INVITE"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AINVITE_TARGET_USERS",
            "name": "INVITE_TARGET_USERS",
            "summary": "GET,\u0020PUT",
            "url": "classes/Discord-Http-Endpoint.html#constant_INVITE_TARGET_USERS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AINVITE_TARGET_USERS_JOB_STATUS",
            "name": "INVITE_TARGET_USERS_JOB_STATUS",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_INVITE_TARGET_USERS_JOB_STATUS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ASTAGE_INSTANCES",
            "name": "STAGE_INSTANCES",
            "summary": "POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_STAGE_INSTANCES"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ASTAGE_INSTANCE",
            "name": "STAGE_INSTANCE",
            "summary": "GET,\u0020PATCH,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_STAGE_INSTANCE"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILDS_TEMPLATE",
            "name": "GUILDS_TEMPLATE",
            "summary": "GET,\u0020POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILDS_TEMPLATE"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_TEMPLATES",
            "name": "GUILD_TEMPLATES",
            "summary": "GET,\u0020POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_TEMPLATES"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_TEMPLATE",
            "name": "GUILD_TEMPLATE",
            "summary": "PUT,\u0020PATCH,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_TEMPLATE"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_AUTO_MODERATION_RULES",
            "name": "GUILD_AUTO_MODERATION_RULES",
            "summary": "GET,\u0020POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_AUTO_MODERATION_RULES"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AGUILD_AUTO_MODERATION_RULE",
            "name": "GUILD_AUTO_MODERATION_RULE",
            "summary": "GET,\u0020PATCH,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_GUILD_AUTO_MODERATION_RULE"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ALOBBIES",
            "name": "LOBBIES",
            "summary": "POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_LOBBIES"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ALOBBY",
            "name": "LOBBY",
            "summary": "GET,\u0020PATCH,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_LOBBY"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ALOBBY_MEMBER",
            "name": "LOBBY_MEMBER",
            "summary": "PUT,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_LOBBY_MEMBER"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ALOBBY_SELF",
            "name": "LOBBY_SELF",
            "summary": "DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_LOBBY_SELF"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ALOBBY_CHANNEL_LINKING",
            "name": "LOBBY_CHANNEL_LINKING",
            "summary": "PATCH",
            "url": "classes/Discord-Http-Endpoint.html#constant_LOBBY_CHANNEL_LINKING"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ASOUNDBOARD_DEFAULT_SOUNDS",
            "name": "SOUNDBOARD_DEFAULT_SOUNDS",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_SOUNDBOARD_DEFAULT_SOUNDS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AUSER_CURRENT",
            "name": "USER_CURRENT",
            "summary": "GET,\u0020PATCH",
            "url": "classes/Discord-Http-Endpoint.html#constant_USER_CURRENT"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AUSER",
            "name": "USER",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_USER"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AUSER_CURRENT_GUILDS",
            "name": "USER_CURRENT_GUILDS",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_USER_CURRENT_GUILDS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AUSER_CURRENT_GUILD",
            "name": "USER_CURRENT_GUILD",
            "summary": "DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_USER_CURRENT_GUILD"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AUSER_CURRENT_MEMBER",
            "name": "USER_CURRENT_MEMBER",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_USER_CURRENT_MEMBER"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AUSER_CURRENT_CHANNELS",
            "name": "USER_CURRENT_CHANNELS",
            "summary": "GET,\u0020POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_USER_CURRENT_CHANNELS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AUSER_CURRENT_CONNECTIONS",
            "name": "USER_CURRENT_CONNECTIONS",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_USER_CURRENT_CONNECTIONS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AUSER_CURRENT_APPLICATION_ROLE_CONNECTION",
            "name": "USER_CURRENT_APPLICATION_ROLE_CONNECTION",
            "summary": "GET,\u0020PUT,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_USER_CURRENT_APPLICATION_ROLE_CONNECTION"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AAPPLICATION",
            "name": "APPLICATION",
            "summary": "GET,\u0020PATCH",
            "url": "classes/Discord-Http-Endpoint.html#constant_APPLICATION"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AAPPLICATION_CURRENT",
            "name": "APPLICATION_CURRENT",
            "summary": "GET,\u0020PATCH",
            "url": "classes/Discord-Http-Endpoint.html#constant_APPLICATION_CURRENT"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AAPPLICATION_ACTIVITY_INSTANCE",
            "name": "APPLICATION_ACTIVITY_INSTANCE",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_APPLICATION_ACTIVITY_INSTANCE"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AWEBHOOK",
            "name": "WEBHOOK",
            "summary": "GET,\u0020PATCH,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_WEBHOOK"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AWEBHOOK_TOKEN",
            "name": "WEBHOOK_TOKEN",
            "summary": "GET,\u0020PATCH,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_WEBHOOK_TOKEN"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AWEBHOOK_EXECUTE",
            "name": "WEBHOOK_EXECUTE",
            "summary": "POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_WEBHOOK_EXECUTE"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AWEBHOOK_EXECUTE_SLACK",
            "name": "WEBHOOK_EXECUTE_SLACK",
            "summary": "POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_WEBHOOK_EXECUTE_SLACK"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AWEBHOOK_EXECUTE_GITHUB",
            "name": "WEBHOOK_EXECUTE_GITHUB",
            "summary": "POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_WEBHOOK_EXECUTE_GITHUB"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AWEBHOOK_MESSAGE",
            "name": "WEBHOOK_MESSAGE",
            "summary": "PATCH,\u0020DELETE",
            "url": "classes/Discord-Http-Endpoint.html#constant_WEBHOOK_MESSAGE"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AAPPLICATION_ROLE_CONNECTION_METADATA",
            "name": "APPLICATION_ROLE_CONNECTION_METADATA",
            "summary": "GET,\u0020PUT",
            "url": "classes/Discord-Http-Endpoint.html#constant_APPLICATION_ROLE_CONNECTION_METADATA"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AAPPLICATION_ATTACHMENT",
            "name": "APPLICATION_ATTACHMENT",
            "summary": "POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_APPLICATION_ATTACHMENT"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AOAUTH2_ME",
            "name": "OAUTH2_ME",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_OAUTH2_ME"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AOAUTH2_APPLICATIONS_ME",
            "name": "OAUTH2_APPLICATIONS_ME",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_OAUTH2_APPLICATIONS_ME"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AOAUTH2_KEYS",
            "name": "OAUTH2_KEYS",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_OAUTH2_KEYS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AOAUTH2_USERINFO",
            "name": "OAUTH2_USERINFO",
            "summary": "GET",
            "url": "classes/Discord-Http-Endpoint.html#constant_OAUTH2_USERINFO"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ALOBBY_MEMBER_ME_INVITES",
            "name": "LOBBY_MEMBER_ME_INVITES",
            "summary": "POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_LOBBY_MEMBER_ME_INVITES"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ALOBBY_MEMBERS_BULK",
            "name": "LOBBY_MEMBERS_BULK",
            "summary": "POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_LOBBY_MEMBERS_BULK"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ALOBBY_MEMBER_INVITES",
            "name": "LOBBY_MEMBER_INVITES",
            "summary": "POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_LOBBY_MEMBER_INVITES"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ALOBBY_MESSAGES",
            "name": "LOBBY_MESSAGES",
            "summary": "GET,\u0020POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_LOBBY_MESSAGES"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003ALOBBY_MESSAGE_MODERATION_METADATA",
            "name": "LOBBY_MESSAGE_MODERATION_METADATA",
            "summary": "PUT",
            "url": "classes/Discord-Http-Endpoint.html#constant_LOBBY_MESSAGE_MODERATION_METADATA"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003APARTNER_SDK_DMS_MESSAGE_MODERATION_METADATA",
            "name": "PARTNER_SDK_DMS_MESSAGE_MODERATION_METADATA",
            "summary": "PUT",
            "url": "classes/Discord-Http-Endpoint.html#constant_PARTNER_SDK_DMS_MESSAGE_MODERATION_METADATA"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003APARTNER_SDK_PROVISIONAL_ACCOUNTS_UNMERGE",
            "name": "PARTNER_SDK_PROVISIONAL_ACCOUNTS_UNMERGE",
            "summary": "POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_PARTNER_SDK_PROVISIONAL_ACCOUNTS_UNMERGE"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003APARTNER_SDK_PROVISIONAL_ACCOUNTS_UNMERGE_BOT",
            "name": "PARTNER_SDK_PROVISIONAL_ACCOUNTS_UNMERGE_BOT",
            "summary": "POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_PARTNER_SDK_PROVISIONAL_ACCOUNTS_UNMERGE_BOT"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003APARTNER_SDK_TOKEN",
            "name": "PARTNER_SDK_TOKEN",
            "summary": "POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_PARTNER_SDK_TOKEN"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003APARTNER_SDK_TOKEN_BOT",
            "name": "PARTNER_SDK_TOKEN_BOT",
            "summary": "POST",
            "url": "classes/Discord-Http-Endpoint.html#constant_PARTNER_SDK_TOKEN_BOT"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AREGEX",
            "name": "REGEX",
            "summary": "Regex\u0020to\u0020identify\u0020parameters\u0020in\u0020endpoints.",
            "url": "classes/Discord-Http-Endpoint.html#constant_REGEX"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003AMAJOR_PARAMETERS",
            "name": "MAJOR_PARAMETERS",
            "summary": "A\u0020list\u0020of\u0020parameters\u0020considered\u0020\u0027major\u0027\u0020by\u0020Discord.",
            "url": "classes/Discord-Http-Endpoint.html#constant_MAJOR_PARAMETERS"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003A\u0024endpoint",
            "name": "endpoint",
            "summary": "The\u0020string\u0020version\u0020of\u0020the\u0020endpoint,\u0020including\u0020all\u0020parameters.",
            "url": "classes/Discord-Http-Endpoint.html#property_endpoint"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003A\u0024vars",
            "name": "vars",
            "summary": "Array\u0020of\u0020placeholders\u0020to\u0020be\u0020replaced\u0020in\u0020the\u0020endpoint.",
            "url": "classes/Discord-Http-Endpoint.html#property_vars"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003A\u0024args",
            "name": "args",
            "summary": "Array\u0020of\u0020arguments\u0020to\u0020substitute\u0020into\u0020the\u0020endpoint.",
            "url": "classes/Discord-Http-Endpoint.html#property_args"
        },                {
            "fqsen": "\\Discord\\Http\\Endpoint\u003A\u003A\u0024query",
            "name": "query",
            "summary": "Array\u0020of\u0020query\u0020data\u0020to\u0020be\u0020appended\nto\u0020the\u0020end\u0020of\u0020the\u0020endpoint\u0020with\u0020\u0060http_build_query\u0060.",
            "url": "classes/Discord-Http-Endpoint.html#property_query"
        },                {
            "fqsen": "\\Discord\\Http\\EndpointInterface",
            "name": "EndpointInterface",
            "summary": "",
            "url": "classes/Discord-Http-EndpointInterface.html"
        },                {
            "fqsen": "\\Discord\\Http\\EndpointInterface\u003A\u003AbindArgs\u0028\u0029",
            "name": "bindArgs",
            "summary": "",
            "url": "classes/Discord-Http-EndpointInterface.html#method_bindArgs"
        },                {
            "fqsen": "\\Discord\\Http\\EndpointInterface\u003A\u003AbindAssoc\u0028\u0029",
            "name": "bindAssoc",
            "summary": "",
            "url": "classes/Discord-Http-EndpointInterface.html#method_bindAssoc"
        },                {
            "fqsen": "\\Discord\\Http\\EndpointInterface\u003A\u003AaddQuery\u0028\u0029",
            "name": "addQuery",
            "summary": "",
            "url": "classes/Discord-Http-EndpointInterface.html#method_addQuery"
        },                {
            "fqsen": "\\Discord\\Http\\EndpointInterface\u003A\u003AtoAbsoluteEndpoint\u0028\u0029",
            "name": "toAbsoluteEndpoint",
            "summary": "",
            "url": "classes/Discord-Http-EndpointInterface.html#method_toAbsoluteEndpoint"
        },                {
            "fqsen": "\\Discord\\Http\\EndpointInterface\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Discord-Http-EndpointInterface.html#method___toString"
        },                {
            "fqsen": "\\Discord\\Http\\EndpointInterface\u003A\u003Abind\u0028\u0029",
            "name": "bind",
            "summary": "",
            "url": "classes/Discord-Http-EndpointInterface.html#method_bind"
        },                {
            "fqsen": "\\Discord\\Http\\EndpointTrait",
            "name": "EndpointTrait",
            "summary": "",
            "url": "classes/Discord-Http-EndpointTrait.html"
        },                {
            "fqsen": "\\Discord\\Http\\EndpointTrait\u003A\u003AbindArgs\u0028\u0029",
            "name": "bindArgs",
            "summary": "Binds\u0020a\u0020list\u0020of\u0020arguments\u0020to\u0020the\u0020endpoint.",
            "url": "classes/Discord-Http-EndpointTrait.html#method_bindArgs"
        },                {
            "fqsen": "\\Discord\\Http\\EndpointTrait\u003A\u003AbindAssoc\u0028\u0029",
            "name": "bindAssoc",
            "summary": "Binds\u0020an\u0020associative\u0020array\u0020to\u0020the\u0020endpoint.",
            "url": "classes/Discord-Http-EndpointTrait.html#method_bindAssoc"
        },                {
            "fqsen": "\\Discord\\Http\\EndpointTrait\u003A\u003AaddQuery\u0028\u0029",
            "name": "addQuery",
            "summary": "Adds\u0020a\u0020key\u002Dvalue\u0020query\u0020pair\u0020to\u0020the\u0020endpoint.",
            "url": "classes/Discord-Http-EndpointTrait.html#method_addQuery"
        },                {
            "fqsen": "\\Discord\\Http\\EndpointTrait\u003A\u003AtoAbsoluteEndpoint\u0028\u0029",
            "name": "toAbsoluteEndpoint",
            "summary": "Converts\u0020the\u0020endpoint\u0020into\u0020the\u0020absolute\u0020endpoint\u0020with\nplaceholders\u0020replaced.",
            "url": "classes/Discord-Http-EndpointTrait.html#method_toAbsoluteEndpoint"
        },                {
            "fqsen": "\\Discord\\Http\\EndpointTrait\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Converts\u0020the\u0020endpoint\u0020to\u0020a\u0020string.",
            "url": "classes/Discord-Http-EndpointTrait.html#method___toString"
        },                {
            "fqsen": "\\Discord\\Http\\EndpointTrait\u003A\u003Abind\u0028\u0029",
            "name": "bind",
            "summary": "Creates\u0020an\u0020endpoint\u0020class\u0020and\u0020binds\u0020arguments\u0020to\nthe\u0020newly\u0020created\u0020instance.",
            "url": "classes/Discord-Http-EndpointTrait.html#method_bind"
        },                {
            "fqsen": "\\Discord\\Http\\EndpointTrait\u003A\u003AisMajorParameter\u0028\u0029",
            "name": "isMajorParameter",
            "summary": "Checks\u0020if\u0020a\u0020parameter\u0020is\u0020a\u0020major\u0020parameter.",
            "url": "classes/Discord-Http-EndpointTrait.html#method_isMajorParameter"
        },                {
            "fqsen": "\\Discord\\Http\\Exceptions\\BadRequestException",
            "name": "BadRequestException",
            "summary": "Thrown\u0020when\u0020a\u0020request\u0020to\u0020Discord\u0027s\u0020REST\u0020API\u0020returned\u0020ClientErrorResponse.",
            "url": "classes/Discord-Http-Exceptions-BadRequestException.html"
        },                {
            "fqsen": "\\Discord\\Http\\Exceptions\\BadRequestException\u003A\u003A\u0024code",
            "name": "code",
            "summary": "",
            "url": "classes/Discord-Http-Exceptions-BadRequestException.html#property_code"
        },                {
            "fqsen": "\\Discord\\Http\\Exceptions\\ContentTooLongException",
            "name": "ContentTooLongException",
            "summary": "Thrown\u0020when\u0020the\u0020Discord\u0020servers\u0020return\u0020\u0060content\u0020longer\u0020than\u00202000\u0020characters\u0060\u0020after\na\u0020REST\u0020request.\u0020The\u0020user\u0020must\u0020use\u0020WebSockets\u0020to\u0020obtain\u0020this\u0020data\u0020if\u0020they\u0020need\u0020it.",
            "url": "classes/Discord-Http-Exceptions-ContentTooLongException.html"
        },                {
            "fqsen": "\\Discord\\Http\\Exceptions\\InvalidTokenException",
            "name": "InvalidTokenException",
            "summary": "Thrown\u0020when\u0020an\u0020invalid\u0020token\u0020is\u0020provided\u0020to\u0020a\u0020Discord\u0020endpoint.",
            "url": "classes/Discord-Http-Exceptions-InvalidTokenException.html"
        },                {
            "fqsen": "\\Discord\\Http\\Exceptions\\InvalidTokenException\u003A\u003A\u0024code",
            "name": "code",
            "summary": "",
            "url": "classes/Discord-Http-Exceptions-InvalidTokenException.html#property_code"
        },                {
            "fqsen": "\\Discord\\Http\\Exceptions\\MethodNotAllowedException",
            "name": "MethodNotAllowedException",
            "summary": "Thrown\u0020when\u0020a\u0020request\u0020to\u0020Discord\u0027s\u0020REST\u0020API\u0020method\u0020is\u0020invalid.",
            "url": "classes/Discord-Http-Exceptions-MethodNotAllowedException.html"
        },                {
            "fqsen": "\\Discord\\Http\\Exceptions\\MethodNotAllowedException\u003A\u003A\u0024code",
            "name": "code",
            "summary": "",
            "url": "classes/Discord-Http-Exceptions-MethodNotAllowedException.html#property_code"
        },                {
            "fqsen": "\\Discord\\Http\\Exceptions\\NoPermissionsException",
            "name": "NoPermissionsException",
            "summary": "Thrown\u0020when\u0020you\u0020do\u0020not\u0020have\u0020permissions\u0020to\u0020do\u0020something.",
            "url": "classes/Discord-Http-Exceptions-NoPermissionsException.html"
        },                {
            "fqsen": "\\Discord\\Http\\Exceptions\\NoPermissionsException\u003A\u003A\u0024code",
            "name": "code",
            "summary": "",
            "url": "classes/Discord-Http-Exceptions-NoPermissionsException.html#property_code"
        },                {
            "fqsen": "\\Discord\\Http\\Exceptions\\NotFoundException",
            "name": "NotFoundException",
            "summary": "Thrown\u0020when\u0020a\u0020404\u0020Not\u0020Found\u0020response\u0020is\u0020received.",
            "url": "classes/Discord-Http-Exceptions-NotFoundException.html"
        },                {
            "fqsen": "\\Discord\\Http\\Exceptions\\NotFoundException\u003A\u003A\u0024code",
            "name": "code",
            "summary": "",
            "url": "classes/Discord-Http-Exceptions-NotFoundException.html#property_code"
        },                {
            "fqsen": "\\Discord\\Http\\Exceptions\\RateLimitException",
            "name": "RateLimitException",
            "summary": "Thrown\u0020when\u0020a\u0020request\u0020to\u0020Discord\u0027s\u0020REST\u0020API\u0020got\u0020rate\u0020limited\u0020and\u0020the\u0020library\ndoes\u0020not\u0020know\u0020how\u0020to\u0020handle.",
            "url": "classes/Discord-Http-Exceptions-RateLimitException.html"
        },                {
            "fqsen": "\\Discord\\Http\\Exceptions\\RateLimitException\u003A\u003A\u0024code",
            "name": "code",
            "summary": "",
            "url": "classes/Discord-Http-Exceptions-RateLimitException.html#property_code"
        },                {
            "fqsen": "\\Discord\\Http\\Exceptions\\RequestFailedException",
            "name": "RequestFailedException",
            "summary": "Thrown\u0020when\u0020a\u0020request\u0020to\u0020Discord\u0027s\u0020REST\u0020API\u0020fails.",
            "url": "classes/Discord-Http-Exceptions-RequestFailedException.html"
        },                {
            "fqsen": "\\Discord\\Http\\Http",
            "name": "Http",
            "summary": "Discord\u0020HTTP\u0020client.",
            "url": "classes/Discord-Http-Http.html"
        },                {
            "fqsen": "\\Discord\\Http\\Http\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Http\u0020wrapper\u0020constructor.",
            "url": "classes/Discord-Http-Http.html#method___construct"
        },                {
            "fqsen": "\\Discord\\Http\\Http\u003A\u003AVERSION",
            "name": "VERSION",
            "summary": "DiscordPHP\u002DHttp\u0020version.",
            "url": "classes/Discord-Http-Http.html#constant_VERSION"
        },                {
            "fqsen": "\\Discord\\Http\\Http\u003A\u003AHTTP_API_VERSION",
            "name": "HTTP_API_VERSION",
            "summary": "Current\u0020Discord\u0020HTTP\u0020API\u0020version.",
            "url": "classes/Discord-Http-Http.html#constant_HTTP_API_VERSION"
        },                {
            "fqsen": "\\Discord\\Http\\Http\u003A\u003ABASE_URL",
            "name": "BASE_URL",
            "summary": "Discord\u0020API\u0020base\u0020URL.",
            "url": "classes/Discord-Http-Http.html#constant_BASE_URL"
        },                {
            "fqsen": "\\Discord\\Http\\Http\u003A\u003ACONCURRENT_REQUESTS",
            "name": "CONCURRENT_REQUESTS",
            "summary": "The\u0020number\u0020of\u0020concurrent\u0020requests\u0020which\u0020can\nbe\u0020executed.",
            "url": "classes/Discord-Http-Http.html#constant_CONCURRENT_REQUESTS"
        },                {
            "fqsen": "\\Discord\\Http\\Http\u003A\u003A\u0024token",
            "name": "token",
            "summary": "Authentication\u0020token.",
            "url": "classes/Discord-Http-Http.html#property_token"
        },                {
            "fqsen": "\\Discord\\Http\\Http\u003A\u003A\u0024logger",
            "name": "logger",
            "summary": "Logger\u0020for\u0020HTTP\u0020requests.",
            "url": "classes/Discord-Http-Http.html#property_logger"
        },                {
            "fqsen": "\\Discord\\Http\\Http\u003A\u003A\u0024driver",
            "name": "driver",
            "summary": "HTTP\u0020driver.",
            "url": "classes/Discord-Http-Http.html#property_driver"
        },                {
            "fqsen": "\\Discord\\Http\\Http\u003A\u003A\u0024loop",
            "name": "loop",
            "summary": "ReactPHP\u0020event\u0020loop.",
            "url": "classes/Discord-Http-Http.html#property_loop"
        },                {
            "fqsen": "\\Discord\\Http\\Http\u003A\u003A\u0024buckets",
            "name": "buckets",
            "summary": "Array\u0020of\u0020request\u0020buckets.",
            "url": "classes/Discord-Http-Http.html#property_buckets"
        },                {
            "fqsen": "\\Discord\\Http\\Http\u003A\u003A\u0024rateLimit",
            "name": "rateLimit",
            "summary": "The\u0020current\u0020rate\u002Dlimit.",
            "url": "classes/Discord-Http-Http.html#property_rateLimit"
        },                {
            "fqsen": "\\Discord\\Http\\Http\u003A\u003A\u0024rateLimitReset",
            "name": "rateLimitReset",
            "summary": "Timer\u0020that\u0020resets\u0020the\u0020current\u0020global\u0020rate\u002Dlimit.",
            "url": "classes/Discord-Http-Http.html#property_rateLimitReset"
        },                {
            "fqsen": "\\Discord\\Http\\Http\u003A\u003A\u0024queue",
            "name": "queue",
            "summary": "Request\u0020queue\u0020to\u0020prevent\u0020API\noverload.",
            "url": "classes/Discord-Http-Http.html#property_queue"
        },                {
            "fqsen": "\\Discord\\Http\\Http\u003A\u003A\u0024unboundQueue",
            "name": "unboundQueue",
            "summary": "Request\u0020queue\u0020to\u0020prevent\u0020API\noverload.",
            "url": "classes/Discord-Http-Http.html#property_unboundQueue"
        },                {
            "fqsen": "\\Discord\\Http\\Http\u003A\u003A\u0024waiting",
            "name": "waiting",
            "summary": "Number\u0020of\u0020requests\u0020that\u0020are\u0020waiting\u0020for\u0020a\u0020response.",
            "url": "classes/Discord-Http-Http.html#property_waiting"
        },                {
            "fqsen": "\\Discord\\Http\\Http\u003A\u003A\u0024promiseV3",
            "name": "promiseV3",
            "summary": "Whether\u0020react\/promise\u0020v3\u0020is\u0020used,\u0020if\u0020false,\u0020using\u0020v2.",
            "url": "classes/Discord-Http-Http.html#property_promiseV3"
        },                {
            "fqsen": "\\Discord\\Http\\HttpInterface",
            "name": "HttpInterface",
            "summary": "Discord\u0020HTTP\u0020client.",
            "url": "classes/Discord-Http-HttpInterface.html"
        },                {
            "fqsen": "\\Discord\\Http\\HttpInterface\u003A\u003AsetDriver\u0028\u0029",
            "name": "setDriver",
            "summary": "",
            "url": "classes/Discord-Http-HttpInterface.html#method_setDriver"
        },                {
            "fqsen": "\\Discord\\Http\\HttpInterface\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Discord-Http-HttpInterface.html#method_get"
        },                {
            "fqsen": "\\Discord\\Http\\HttpInterface\u003A\u003Apost\u0028\u0029",
            "name": "post",
            "summary": "",
            "url": "classes/Discord-Http-HttpInterface.html#method_post"
        },                {
            "fqsen": "\\Discord\\Http\\HttpInterface\u003A\u003Aput\u0028\u0029",
            "name": "put",
            "summary": "",
            "url": "classes/Discord-Http-HttpInterface.html#method_put"
        },                {
            "fqsen": "\\Discord\\Http\\HttpInterface\u003A\u003Apatch\u0028\u0029",
            "name": "patch",
            "summary": "",
            "url": "classes/Discord-Http-HttpInterface.html#method_patch"
        },                {
            "fqsen": "\\Discord\\Http\\HttpInterface\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/Discord-Http-HttpInterface.html#method_delete"
        },                {
            "fqsen": "\\Discord\\Http\\HttpInterface\u003A\u003AqueueRequest\u0028\u0029",
            "name": "queueRequest",
            "summary": "",
            "url": "classes/Discord-Http-HttpInterface.html#method_queueRequest"
        },                {
            "fqsen": "\\Discord\\Http\\HttpInterface\u003A\u003AisUnboundEndpoint\u0028\u0029",
            "name": "isUnboundEndpoint",
            "summary": "",
            "url": "classes/Discord-Http-HttpInterface.html#method_isUnboundEndpoint"
        },                {
            "fqsen": "\\Discord\\Http\\HttpInterface\u003A\u003AhandleError\u0028\u0029",
            "name": "handleError",
            "summary": "",
            "url": "classes/Discord-Http-HttpInterface.html#method_handleError"
        },                {
            "fqsen": "\\Discord\\Http\\HttpInterface\u003A\u003AgetUserAgent\u0028\u0029",
            "name": "getUserAgent",
            "summary": "",
            "url": "classes/Discord-Http-HttpInterface.html#method_getUserAgent"
        },                {
            "fqsen": "\\Discord\\Http\\HttpTrait",
            "name": "HttpTrait",
            "summary": "Discord\u0020HTTP\u0020client.",
            "url": "classes/Discord-Http-HttpTrait.html"
        },                {
            "fqsen": "\\Discord\\Http\\HttpTrait\u003A\u003AsetDriver\u0028\u0029",
            "name": "setDriver",
            "summary": "Sets\u0020the\u0020driver\u0020of\u0020the\u0020HTTP\u0020client.",
            "url": "classes/Discord-Http-HttpTrait.html#method_setDriver"
        },                {
            "fqsen": "\\Discord\\Http\\HttpTrait\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Runs\u0020a\u0020GET\u0020request.",
            "url": "classes/Discord-Http-HttpTrait.html#method_get"
        },                {
            "fqsen": "\\Discord\\Http\\HttpTrait\u003A\u003Apost\u0028\u0029",
            "name": "post",
            "summary": "Runs\u0020a\u0020POST\u0020request.",
            "url": "classes/Discord-Http-HttpTrait.html#method_post"
        },                {
            "fqsen": "\\Discord\\Http\\HttpTrait\u003A\u003Aput\u0028\u0029",
            "name": "put",
            "summary": "Runs\u0020a\u0020PUT\u0020request.",
            "url": "classes/Discord-Http-HttpTrait.html#method_put"
        },                {
            "fqsen": "\\Discord\\Http\\HttpTrait\u003A\u003Apatch\u0028\u0029",
            "name": "patch",
            "summary": "Runs\u0020a\u0020PATCH\u0020request.",
            "url": "classes/Discord-Http-HttpTrait.html#method_patch"
        },                {
            "fqsen": "\\Discord\\Http\\HttpTrait\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Runs\u0020a\u0020DELETE\u0020request.",
            "url": "classes/Discord-Http-HttpTrait.html#method_delete"
        },                {
            "fqsen": "\\Discord\\Http\\HttpTrait\u003A\u003AqueueRequest\u0028\u0029",
            "name": "queueRequest",
            "summary": "Builds\u0020and\u0020queues\u0020a\u0020request.",
            "url": "classes/Discord-Http-HttpTrait.html#method_queueRequest"
        },                {
            "fqsen": "\\Discord\\Http\\HttpTrait\u003A\u003AguessContent\u0028\u0029",
            "name": "guessContent",
            "summary": "Guesses\u0020the\u0020headers\u0020and\u0020transforms\u0020the\u0020content\u0020of\u0020a\u0020request.",
            "url": "classes/Discord-Http-HttpTrait.html#method_guessContent"
        },                {
            "fqsen": "\\Discord\\Http\\HttpTrait\u003A\u003AexecuteRequest\u0028\u0029",
            "name": "executeRequest",
            "summary": "Executes\u0020a\u0020request.",
            "url": "classes/Discord-Http-HttpTrait.html#method_executeRequest"
        },                {
            "fqsen": "\\Discord\\Http\\HttpTrait\u003A\u003AsortIntoBucket\u0028\u0029",
            "name": "sortIntoBucket",
            "summary": "Sorts\u0020a\u0020request\u0020into\u0020a\u0020bucket.",
            "url": "classes/Discord-Http-HttpTrait.html#method_sortIntoBucket"
        },                {
            "fqsen": "\\Discord\\Http\\HttpTrait\u003A\u003AgetBucket\u0028\u0029",
            "name": "getBucket",
            "summary": "Gets\u0020a\u0020bucket.",
            "url": "classes/Discord-Http-HttpTrait.html#method_getBucket"
        },                {
            "fqsen": "\\Discord\\Http\\HttpTrait\u003A\u003AcheckQueue\u0028\u0029",
            "name": "checkQueue",
            "summary": "Checks\u0020the\u0020request\u0020queue\u0020to\u0020see\u0020if\u0020more\u0020requests\u0020can\u0020be\nsent\u0020out.",
            "url": "classes/Discord-Http-HttpTrait.html#method_checkQueue"
        },                {
            "fqsen": "\\Discord\\Http\\HttpTrait\u003A\u003AcheckunboundQueue\u0028\u0029",
            "name": "checkunboundQueue",
            "summary": "Checks\u0020the\u0020interaction\u0020queue\u0020to\u0020see\u0020if\u0020more\u0020requests\u0020can\u0020be\nsent\u0020out.",
            "url": "classes/Discord-Http-HttpTrait.html#method_checkunboundQueue"
        },                {
            "fqsen": "\\Discord\\Http\\HttpTrait\u003A\u003AisUnboundEndpoint\u0028\u0029",
            "name": "isUnboundEndpoint",
            "summary": "Checks\u0020if\u0020the\u0020request\u0020is\u0020for\u0020an\u0020endpoint\u0020not\u0020bound\u0020by\u0020the\u0020global\u0020rate\u0020limit.",
            "url": "classes/Discord-Http-HttpTrait.html#method_isUnboundEndpoint"
        },                {
            "fqsen": "\\Discord\\Http\\HttpTrait\u003A\u003AhandleError\u0028\u0029",
            "name": "handleError",
            "summary": "Returns\u0020an\u0020exception\u0020based\u0020on\u0020the\u0020request.",
            "url": "classes/Discord-Http-HttpTrait.html#method_handleError"
        },                {
            "fqsen": "\\Discord\\Http\\HttpTrait\u003A\u003AgetUserAgent\u0028\u0029",
            "name": "getUserAgent",
            "summary": "Returns\u0020the\u0020User\u002DAgent\u0020of\u0020the\u0020HTTP\u0020client.",
            "url": "classes/Discord-Http-HttpTrait.html#method_getUserAgent"
        },                {
            "fqsen": "\\Discord\\Http\\Multipart\\MultipartBody",
            "name": "MultipartBody",
            "summary": "",
            "url": "classes/Discord-Http-Multipart-MultipartBody.html"
        },                {
            "fqsen": "\\Discord\\Http\\Multipart\\MultipartBody\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Discord-Http-Multipart-MultipartBody.html#method___construct"
        },                {
            "fqsen": "\\Discord\\Http\\Multipart\\MultipartBody\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Discord-Http-Multipart-MultipartBody.html#method___toString"
        },                {
            "fqsen": "\\Discord\\Http\\Multipart\\MultipartBody\u003A\u003AgetHeaders\u0028\u0029",
            "name": "getHeaders",
            "summary": "",
            "url": "classes/Discord-Http-Multipart-MultipartBody.html#method_getHeaders"
        },                {
            "fqsen": "\\Discord\\Http\\Multipart\\MultipartBody\u003A\u003ABOUNDARY",
            "name": "BOUNDARY",
            "summary": "",
            "url": "classes/Discord-Http-Multipart-MultipartBody.html#constant_BOUNDARY"
        },                {
            "fqsen": "\\Discord\\Http\\Multipart\\MultipartBody\u003A\u003A\u0024fields",
            "name": "fields",
            "summary": "",
            "url": "classes/Discord-Http-Multipart-MultipartBody.html#property_fields"
        },                {
            "fqsen": "\\Discord\\Http\\Multipart\\MultipartBody\u003A\u003A\u0024boundary",
            "name": "boundary",
            "summary": "",
            "url": "classes/Discord-Http-Multipart-MultipartBody.html#property_boundary"
        },                {
            "fqsen": "\\Discord\\Http\\Multipart\\MultipartField",
            "name": "MultipartField",
            "summary": "",
            "url": "classes/Discord-Http-Multipart-MultipartField.html"
        },                {
            "fqsen": "\\Discord\\Http\\Multipart\\MultipartField\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Discord-Http-Multipart-MultipartField.html#method___construct"
        },                {
            "fqsen": "\\Discord\\Http\\Multipart\\MultipartField\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Discord-Http-Multipart-MultipartField.html#method___toString"
        },                {
            "fqsen": "\\Discord\\Http\\Multipart\\MultipartField\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Discord-Http-Multipart-MultipartField.html#property_name"
        },                {
            "fqsen": "\\Discord\\Http\\Multipart\\MultipartField\u003A\u003A\u0024content",
            "name": "content",
            "summary": "",
            "url": "classes/Discord-Http-Multipart-MultipartField.html#property_content"
        },                {
            "fqsen": "\\Discord\\Http\\Multipart\\MultipartField\u003A\u003A\u0024headers",
            "name": "headers",
            "summary": "",
            "url": "classes/Discord-Http-Multipart-MultipartField.html#property_headers"
        },                {
            "fqsen": "\\Discord\\Http\\Multipart\\MultipartField\u003A\u003A\u0024fileName",
            "name": "fileName",
            "summary": "",
            "url": "classes/Discord-Http-Multipart-MultipartField.html#property_fileName"
        },                {
            "fqsen": "\\Discord\\Http\\RateLimit",
            "name": "RateLimit",
            "summary": "Represents\u0020a\u0020rate\u002Dlimit\u0020given\u0020by\u0020Discord.",
            "url": "classes/Discord-Http-RateLimit.html"
        },                {
            "fqsen": "\\Discord\\Http\\RateLimit\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Rate\u0020limit\u0020constructor.",
            "url": "classes/Discord-Http-RateLimit.html#method___construct"
        },                {
            "fqsen": "\\Discord\\Http\\RateLimit\u003A\u003AisGlobal\u0028\u0029",
            "name": "isGlobal",
            "summary": "Gets\u0020the\u0020global\u0020parameter.",
            "url": "classes/Discord-Http-RateLimit.html#method_isGlobal"
        },                {
            "fqsen": "\\Discord\\Http\\RateLimit\u003A\u003AgetRetryAfter\u0028\u0029",
            "name": "getRetryAfter",
            "summary": "Gets\u0020the\u0020retry\u0020after\u0020parameter.",
            "url": "classes/Discord-Http-RateLimit.html#method_getRetryAfter"
        },                {
            "fqsen": "\\Discord\\Http\\RateLimit\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Converts\u0020a\u0020rate\u002Dlimit\u0020to\u0020a\u0020user\u002Dreadable\u0020string.",
            "url": "classes/Discord-Http-RateLimit.html#method___toString"
        },                {
            "fqsen": "\\Discord\\Http\\RateLimit\u003A\u003A\u0024global",
            "name": "global",
            "summary": "Whether\u0020the\u0020rate\u002Dlimit\u0020is\u0020global.",
            "url": "classes/Discord-Http-RateLimit.html#property_global"
        },                {
            "fqsen": "\\Discord\\Http\\RateLimit\u003A\u003A\u0024retry_after",
            "name": "retry_after",
            "summary": "Time\u0020in\u0020seconds\u0020of\u0020when\u0020to\u0020retry\u0020after.",
            "url": "classes/Discord-Http-RateLimit.html#property_retry_after"
        },                {
            "fqsen": "\\Discord\\Http\\Request",
            "name": "Request",
            "summary": "Represents\u0020an\u0020HTTP\u0020request.",
            "url": "classes/Discord-Http-Request.html"
        },                {
            "fqsen": "\\Discord\\Http\\Request\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Request\u0020constructor.",
            "url": "classes/Discord-Http-Request.html#method___construct"
        },                {
            "fqsen": "\\Discord\\Http\\Request\u003A\u003AgetMethod\u0028\u0029",
            "name": "getMethod",
            "summary": "Gets\u0020the\u0020method.",
            "url": "classes/Discord-Http-Request.html#method_getMethod"
        },                {
            "fqsen": "\\Discord\\Http\\Request\u003A\u003AgetUrl\u0028\u0029",
            "name": "getUrl",
            "summary": "Gets\u0020the\u0020url.",
            "url": "classes/Discord-Http-Request.html#method_getUrl"
        },                {
            "fqsen": "\\Discord\\Http\\Request\u003A\u003AgetContent\u0028\u0029",
            "name": "getContent",
            "summary": "Gets\u0020the\u0020content.",
            "url": "classes/Discord-Http-Request.html#method_getContent"
        },                {
            "fqsen": "\\Discord\\Http\\Request\u003A\u003AgetHeaders\u0028\u0029",
            "name": "getHeaders",
            "summary": "Gets\u0020the\u0020headers.",
            "url": "classes/Discord-Http-Request.html#method_getHeaders"
        },                {
            "fqsen": "\\Discord\\Http\\Request\u003A\u003AgetDeferred\u0028\u0029",
            "name": "getDeferred",
            "summary": "Returns\u0020the\u0020deferred\u0020promise.",
            "url": "classes/Discord-Http-Request.html#method_getDeferred"
        },                {
            "fqsen": "\\Discord\\Http\\Request\u003A\u003AgetBucketID\u0028\u0029",
            "name": "getBucketID",
            "summary": "Returns\u0020the\u0020bucket\u0020ID\u0020for\u0020the\u0020request.",
            "url": "classes/Discord-Http-Request.html#method_getBucketID"
        },                {
            "fqsen": "\\Discord\\Http\\Request\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Converts\u0020the\u0020request\u0020to\u0020a\u0020user\u002Dreadable\u0020string.",
            "url": "classes/Discord-Http-Request.html#method___toString"
        },                {
            "fqsen": "\\Discord\\Http\\Request\u003A\u003A\u0024deferred",
            "name": "deferred",
            "summary": "Deferred\u0020promise.",
            "url": "classes/Discord-Http-Request.html#property_deferred"
        },                {
            "fqsen": "\\Discord\\Http\\Request\u003A\u003A\u0024method",
            "name": "method",
            "summary": "Request\u0020method.",
            "url": "classes/Discord-Http-Request.html#property_method"
        },                {
            "fqsen": "\\Discord\\Http\\Request\u003A\u003A\u0024url",
            "name": "url",
            "summary": "Request\u0020URL.",
            "url": "classes/Discord-Http-Request.html#property_url"
        },                {
            "fqsen": "\\Discord\\Http\\Request\u003A\u003A\u0024content",
            "name": "content",
            "summary": "Request\u0020content.",
            "url": "classes/Discord-Http-Request.html#property_content"
        },                {
            "fqsen": "\\Discord\\Http\\Request\u003A\u003A\u0024headers",
            "name": "headers",
            "summary": "Request\u0020headers.",
            "url": "classes/Discord-Http-Request.html#property_headers"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Discord\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/discord-http.html"
        },                {
            "fqsen": "\\Discord",
            "name": "Discord",
            "summary": "",
            "url": "namespaces/discord.html"
        },                {
            "fqsen": "\\Discord\\Http\\Drivers",
            "name": "Drivers",
            "summary": "",
            "url": "namespaces/discord-http-drivers.html"
        },                {
            "fqsen": "\\Discord\\Http\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/discord-http-exceptions.html"
        },                {
            "fqsen": "\\Discord\\Http\\Multipart",
            "name": "Multipart",
            "summary": "",
            "url": "namespaces/discord-http-multipart.html"
        }            ]
);
